### PR TITLE
RATIS-594 RATIS-593 RATIS-551 Add HadoopMetrics2Adaptor for dropwizard metrics and Graphite container for log service

### PR DESCRIPTION
**Pull request by ankitsinghal**

### CODE REVIEW

**Comment by joshelser** [comment]
Can confirm that the graphite wiring up works!
Screen Shot 2019-06-25 at 6 50 27 PM

One thing that looks curious is that we only ever have one metric per raft group. I would expect to see the full set of metrics for every group. This makes me think that something is de-duplicating them based on the final component of the metric name.

For example, instead of having sizeRequestTime_min for every "group_*", we only have one instance in "group_1C0AE431061C". I'm not sure if this is a bug in the Ratis metrics work or in the Reporter.

**Comment by joshelser** [comment]
> This makes me think that something is de-duplicating them based on the final component of the metric name.

Reading through the metrics adapter again, I'm reminded that it's just tracking HashMaps of "name" to metric object (e.g. timer, counter, histogram).

IIRC, the nice hierarchy you have here in the metrics breakdown is via some magic prefix in the name itself (at least, JMX worked this way). Maybe the final name being exported from Ratis is identical, regardless of the RAFT Group (logservice "log") that the LogServer is operating on? That seems plausible given what else I'm seeing..

**Comment by joshelser** [comment]
I dunno, now I'm confused. After letting it run for a bit, I'm seeing more metrics for every Group, but still not every metric. I'm not sure if it's working as intended (just with some delay) or if there is a problem here.

**Comment by joshelser** [comment]
Trying this one out again locally. Is 4d6d1b3 unrelated cleanup, or does it help with the metrics seeming to take a while to show up?

**Comment by joshelser** [comment]
Was chatting with @cbaenziger about this one. He said that he had seen some weirdness with Graphite before and made the suggestion to dump metrics to a file, instead, to make sure things are kosher.

Ankit did this last night and sent me a snippet:
```
1562637060111 default.ratis_log_worker: rate_unit=events/second,
duration_unit=milliseconds,
Hostname=95cf0993af3d,
ratis_core.ratis_log_worker.worker3.logservice.ratis.org_9999.dataQueueSize=0,
ratis_core.ratis_log_worker.worker3.logservice.ratis.org_9999.flush-time_count=354,
ratis_core.ratis_log_worker.worker3.logservice.ratis.org_9999.flush-time_mean_rate=8.960493797929672,
ratis_core.ratis_log_worker.worker3.logservice.ratis.org_9999.flush-time_1min_rate=0.3611728880545569,
ratis_core.ratis_log_worker.worker3.logservice.ratis.org_9999.flush-time_5min_rate=0.23055312214233942,
ratis_core.ratis_log_worker.worker3.logservice.ratis.org_9999.flush-time_15min_rate=0.210063676081711,
ratis_core.ratis_log_worker.worker3.logservice.ratis.org_9999.flush-time_mean=2.313851403002056,
ratis_core.ratis_log_worker.worker3.logservice.ratis.org_9999.flush-time_min=0.6128,
ratis_core.ratis_log_worker.worker3.logservice.ratis.org_9999.flush-time_max=48.1075,
ratis_core.ratis_log_worker.worker3.logservice.ratis.org_9999.flush-time_median=1.0378,
ratis_core.ratis_log_worker.worker3.logservice.ratis.org_9999.flush-time_stddev=4.271122297168547,
ratis_core.ratis_log_worker.worker3.logservice.ratis.org_9999.flush-time_75thpercentile=1.8774,
ratis_core.ratis_log_worker.worker3.logservice.ratis.org_9999.flush-time_95thpercentile=7.826,
ratis_core.ratis_log_worker.worker3.logservice.ratis.org_9999.flush-time_98thpercentile=15.2421,
ratis_core.ratis_log_worker.worker3.logservice.ratis.org_9999.flush-time_99thpercentile=28.5539,
ratis_core.ratis_log_worker.worker3.logservice.ratis.org_9999.flush-time_999thpercentile=48.1075

1562637060114 default.log_statemachine: rate_unit=events/second,
duration_unit=milliseconds,
Hostname=95cf0993af3d,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.appendRequestTime_count=57,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.appendRequestTime_mean_rate=7.863823737109227,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.appendRequestTime_1min_rate=5.2,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.appendRequestTime_5min_rate=5.2,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.appendRequestTime_15min_rate=5.2,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.appendRequestTime_mean=1.5375387308711765,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.appendRequestTime_min=0.043,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.appendRequestTime_max=64.4686,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.appendRequestTime_median=0.0881,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.appendRequestTime_stddev=8.626373430873711,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.appendRequestTime_75thpercentile=0.1148,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.appendRequestTime_95thpercentile=0.5464,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.appendRequestTime_98thpercentile=20.9274,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.appendRequestTime_99thpercentile=64.4686,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.appendRequestTime_999thpercentile=64.4686,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.getCloseLogTime_count=0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.getCloseLogTime_mean_rate=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.getCloseLogTime_1min_rate=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.getCloseLogTime_5min_rate=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.getCloseLogTime_15min_rate=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.getCloseLogTime_mean=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.getCloseLogTime_min=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.getCloseLogTime_max=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.getCloseLogTime_median=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.getCloseLogTime_stddev=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.getCloseLogTime_75thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.getCloseLogTime_95thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.getCloseLogTime_98thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.getCloseLogTime_99thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.getCloseLogTime_999thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.getStateTime_count=0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.getStateTime_mean_rate=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.getStateTime_1min_rate=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.getStateTime_5min_rate=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.getStateTime_15min_rate=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.getStateTime_mean=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.getStateTime_min=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.getStateTime_max=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.getStateTime_median=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.getStateTime_stddev=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.getStateTime_75thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.getStateTime_95thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.getStateTime_98thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.getStateTime_99thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.getStateTime_999thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.lastIndexQueryTime_count=0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.lastIndexQueryTime_mean_rate=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.lastIndexQueryTime_1min_rate=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.lastIndexQueryTime_5min_rate=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.lastIndexQueryTime_15min_rate=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.lastIndexQueryTime_mean=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.lastIndexQueryTime_min=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.lastIndexQueryTime_max=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.lastIndexQueryTime_median=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.lastIndexQueryTime_stddev=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.lastIndexQueryTime_75thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.lastIndexQueryTime_95thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.lastIndexQueryTime_98thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.lastIndexQueryTime_99thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.lastIndexQueryTime_999thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.lengthQueryTime_count=0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.lengthQueryTime_mean_rate=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.lengthQueryTime_1min_rate=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.lengthQueryTime_5min_rate=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.lengthQueryTime_15min_rate=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.lengthQueryTime_mean=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.lengthQueryTime_min=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.lengthQueryTime_max=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.lengthQueryTime_median=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.lengthQueryTime_stddev=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.lengthQueryTime_75thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.lengthQueryTime_95thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.lengthQueryTime_98thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.lengthQueryTime_99thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.lengthQueryTime_999thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.readNextQueryTime_count=0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.readNextQueryTime_mean_rate=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.readNextQueryTime_1min_rate=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.readNextQueryTime_5min_rate=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.readNextQueryTime_15min_rate=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.readNextQueryTime_mean=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.readNextQueryTime_min=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.readNextQueryTime_max=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.readNextQueryTime_median=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.readNextQueryTime_stddev=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.readNextQueryTime_75thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.readNextQueryTime_95thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.readNextQueryTime_98thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.readNextQueryTime_99thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.readNextQueryTime_999thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.sizeRequestTime_count=0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.sizeRequestTime_mean_rate=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.sizeRequestTime_1min_rate=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.sizeRequestTime_5min_rate=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.sizeRequestTime_15min_rate=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.sizeRequestTime_mean=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.sizeRequestTime_min=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.sizeRequestTime_max=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.sizeRequestTime_median=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.sizeRequestTime_stddev=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.sizeRequestTime_75thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.sizeRequestTime_95thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.sizeRequestTime_98thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.sizeRequestTime_99thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.sizeRequestTime_999thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.startIndexTime_count=0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.startIndexTime_mean_rate=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.startIndexTime_1min_rate=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.startIndexTime_5min_rate=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.startIndexTime_15min_rate=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.startIndexTime_mean=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.startIndexTime_min=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.startIndexTime_max=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.startIndexTime_median=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.startIndexTime_stddev=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.startIndexTime_75thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.startIndexTime_95thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.startIndexTime_98thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.startIndexTime_99thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.startIndexTime_999thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.syncRequesTime_count=0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.syncRequesTime_mean_rate=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.syncRequesTime_1min_rate=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.syncRequesTime_5min_rate=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.syncRequesTime_15min_rate=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.syncRequesTime_mean=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.syncRequesTime_min=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.syncRequesTime_max=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.syncRequesTime_median=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.syncRequesTime_stddev=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.syncRequesTime_75thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.syncRequesTime_95thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.syncRequesTime_98thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.syncRequesTime_99thpercentile=0.0,
ratis_log_service.log_statemachine.group-E34E02D7E77E.worker3.logservice.ratis.org_9999.syncRequesTime_999thpercentile=0.0
```

Looks like we have everything!

**Comment by joshelser** [comment]
Let me see if I can push a commit to Ankit's branch to set up the file sink for metrics2 as well as graphite. Then I think this is good to go.

**Comment by ankitsinghal** [comment]
> Let me see if I can push a commit to Ankit's branch to set up the file sink for metrics2 as well as graphite. Then I think this is good to go.

I think we already have FileSink and Graphite configured for our docker setup, https://github.com/apache/incubator-ratis/pull/26/files#diff-d0d5cceab64a5304230bebafc6fcfa4d

**Comment by joshelser** [comment]
Aha! Sorry, Ankit. I must have been looking at a stale version of the PR.

Let me validate locally and then merge.

**Comment by joshelser** [comment]
I've gone ahead and merged this. Thanks for the contribution, Ankit!

Digging through the metrics file sink, we can see some good results coming out. This is a very nice addition.

**Pull request closed without merging**
