### PR TITLE
RATIS-1209. Compare the performance between DataStreamApi and AsyncApi.

### PR DESCRIPTION
**Pull request by szetszwo**
See https://issues.apache.org/jira/browse/RATIS-1209

### CODE REVIEW

**Comment by szetszwo** [comment]
@runzhiwang , could you see if this can make DirectByteBuffer faster than async?

**Comment by runzhiwang** [comment]
@szetszwo  I test it, and throw exception.
image

**Comment by szetszwo** [comment]
Oops, I should use ByteBuf to read the file.

@runzhiwang , could you try it again?

**Comment by runzhiwang** [comment]
@szetszwo Sure, will try it tomorrow, off duty now, sorry.

**Comment by szetszwo** [comment]
@runzhiwang , sure thanks.  Take your time.  :)

**Comment by szetszwo** [comment]
Replacing this pull request with https://github.com/apache/incubator-ratis/pull/328 in order to fix the branch.

**Pull request closed without merging**
