### PR TITLE
RATIS-932. Avoid usage of ratis-thirdparty-hadoop in ratis-hadoop module.

### PR DESCRIPTION
**Pull request by mukul1987**
This patch avoids dependency of Ratis on ratis-hadoop-thirdparty, and takes a direct dependency on Hadoop. This helps in simplifying dependency management in Ratis.

### CODE REVIEW

**Comment by mukul1987** [comment]
Thanks for the review @lokeshj1703 , I did a quick compare of the file ProtobufRpcEngine and also reading from the comments on the file. The file is a copy of ProtobufRpcEngine to use the shaded library. It is safe to remove the reference.

/**
 * Copied from {@link org.apache.hadoop.ipc.ProtobufRpcEngine}
 * and replaced the protobuf classes with the shaded classes.
 */

**Comment by lokeshj1703** [comment]
@mukul1987 Thanks for the clarification! I'm +1 on the PR.

**Comment by lokeshj1703** [comment]
@mukul1987 the hadoop tests are failing with the PR. It might be related to the ProtobufRpcEngineShaded file. By default hadoop tests are disabled so failure did not show up in acceptance tests.

**Comment by szetszwo** [comment]
+1 the change looks good.

**Comment by lokeshj1703** [comment]
@mukul1987 We can fix the tests as part of separate jira. +1 for the PR.

**Pull request merged**
