### PR TITLE
RATIS-1141. Class.getSimpleName() has a 4% overhead in the SegmentedRaftLogWriter thread.

### PR DESCRIPTION
**Pull request by szetszwo**
See https://issues.apache.org/jira/browse/RATIS-1141

### CODE REVIEW

**Review by runzhiwang — APPROVED** [review]
LGTM.  waiting CI passed.

**Comment by runzhiwang** [comment]
Reopen pr to trigger CI

**Comment by runzhiwang** [comment]
@szetszwo Do not know why compile failed, I have open it 4 times, compile always failed.

**Comment by szetszwo** [comment]
@runzhiwang , thanks for checking.  TestArithmetic and TestCounter do not compile since the "throws IOException" was removed from ParameterizedBaseTest.  Just have fixed it.

**Pull request merged**
