### PR TITLE
RATIS-978. Fix failed UT: testAddNewFollowers

### PR DESCRIPTION
**Pull request by runzhiwang**
## What changes were proposed in this pull request?

When leader send install snapshot request to follower, leader will [wait](https://github.com/apache/incubator-ratis/blob/master/ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java#L480), but when leader receive the response of install snapshot, leader does not notify.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/RATIS-978

## How was this patch tested?

Existed tests

### CODE REVIEW

**Comment by runzhiwang** [comment]
@bshashikant @lokeshj1703 Could you help review this patch ? Thank you very much.

**Comment by bshashikant** [comment]
Thanks @runzhiwang for working on this. The change looks ok. But , don't we need to check if request for install snapshot is just a notification but not a real snapshot install?

@lokeshj1703 , can you also check?

**Comment by runzhiwang** [comment]
@lokeshj1703 Thanks for review. I have updated.

**Comment by lokeshj1703** [comment]
@runzhiwang Thanks for the contribution! @bshashikant Thanks for review! I have committed the PR to master branch.

**Pull request closed without merging**
