### PR TITLE
RATIS-1138. Add dataStreamAddress to RaftPeer.

### PR DESCRIPTION
**Pull request by szetszwo**
See https://issues.apache.org/jira/browse/RATIS-1138

### CODE REVIEW

**Comment by amaliujia** [comment]
This is actually what I have been adding in the e2e test change :)

**Comment by amaliujia** [comment]
You will also need to update https://github.com/apache/incubator-ratis/blob/7172da0b965e295da815c2ce32deebe06c6e16ea/ratis-netty/src/main/java/org/apache/ratis/netty/client/NettyClientStreamRpc.java#L66

NettyClientStreamRpc uses `server.getDataSteamServerAddress` to build client connection to peers.

**Comment by amaliujia** [comment]
Oops. Sorry for my last comment. You have changed the NettyClientStreamRpc

**Comment by amaliujia** [comment]
LGTM

**Review by runzhiwang — APPROVED** [review]
LGTM

**Comment by runzhiwang** [comment]
reopen pr to trigger ci

**Comment by szetszwo** [comment]
It finally passed all the tests.

Thanks @runzhiwang  for reviewing this.

**Pull request merged**
