### PR TITLE
RATIS-1090. Implement RaftClient.getDataStreamApi

### PR DESCRIPTION
**Pull request by runzhiwang**
## What changes were proposed in this pull request?

 Implement RaftClient.getDataStreamApi

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/RATIS-1090

## How was this patch tested?

Existed ut.

### CODE REVIEW

**Comment by runzhiwang** [comment]
@szetszwo Could you help review this patch ? Thanks a lot.

**Review by szetszwo — COMMENTED** [review]
The change looks good.  Just some minor comments.

**Comment by runzhiwang** [comment]
@szetszwo I have updated the patch. Could you help review it again ?

**Review by szetszwo — APPROVED** [review]
+1 the change looks good.

**Pull request merged**
