### PR TITLE
RATIS-1213. Provide a default implementation for DataStreamApi.stream()

### PR DESCRIPTION
**Pull request by amaliujia**
## What changes were proposed in this pull request?

We can provide a default implementation for ``DataStreamOutput stream();` so it can reuse existing code.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/RATIS-1213

## How was this patch tested?

UT

### CODE REVIEW

**Comment by amaliujia** [comment]
R @runzhiwang @szetszwo

**Comment by szetszwo** [comment]
Let's keep DataStreamApi.stream() for convenience. We may provide a default implementation and remove DataStreamClientImpl.stream() though.
```
+++ b/ratis-client/src/main/java/org/apache/ratis/client/api/DataStreamApi.java
@@ -38,7 +38,9 @@ import java.nio.ByteBuffer;
  */
 public interface DataStreamApi {
   /** Create a stream to write data. */
-  DataStreamOutput stream();
+  default DataStreamOutput stream() {
+    return stream(null);
+  }
```

**Review by szetszwo — APPROVED** [review]
+1 thanks a lot for working on this.

**Review by runzhiwang — APPROVED** [review]
LGTM

**Pull request merged**
