### PR TITLE
RATIS-935. Fix memory leak by ungister metrics

### PR DESCRIPTION
**Pull request by runzhiwang**
This pr do the following:
1. unregister `GrpcServerMetrics`, `LogServiceMetrics`, `LogServiceMetaDataMetrics`, `RaftServerMetrics`, when close or stop, otherwise memory leak.
2. Refactor `GrpcServerMetrics` by extending `RatisMetrics`, so that we can use the common method `create` and `unregister`.
3. Refactor `LogServiceMetricsRegistry` by splitting it into `LogServiceMetrics` and `LogServiceMetaDataMetrics`, just keep the origin logic.
4. Both `LogServiceMetrics` and `LogServiceMetaDataMetrics` extend `RatisMetrics`.

### CODE REVIEW

**Comment by runzhiwang** [comment]
@avijayanhwx Could you help review this patch ?

**Comment by avijayanhwx** [comment]
> @bshashikant @avijayanhwx Could you help review this patch ?
> I think `GrpcServerMetrics `and `LogServiceMetricsRegistry `should extend `RatisMetrics`, then we do not need to define `register `and `unregister `in `GrpcServerMetrics `and `LogServiceMetricsRegistry`. If you agree, I will open another PR to refactor code.

I agree. We should to this refactoring.

**Comment by runzhiwang** [comment]
> Any reason why we cannot do it in this PR, given we are fixing the problem with those 2 metric classes

@avijayanhwx Yeah, I will do it in this PR.

**Comment by runzhiwang** [comment]
@avijayanhwx  I have refactored the code.  Could you help review it again ?

**Comment by avijayanhwx** [comment]
Thank you for the patch @runzhiwang . LGTM +1 (non-binding)

**Comment by avijayanhwx** [comment]
cc @bshashikant  / @lokeshj1703

**Comment by bshashikant** [comment]
thanks @runzhiwang for working on this and @avijayanhwx for the review. I have committed this.

**Pull request merged**
