### PR TITLE
RATIS-1288. Add summary of failures to CI checks 

### PR DESCRIPTION
**Pull request by amaliujia**
## What changes were proposed in this pull request?

add summary of failures to CI checks 

## What is the link to the Apache JIRA

TBD

## How was this patch tested?

N/A

### CODE REVIEW

**Comment by amaliujia** [comment]
R: @runzhiwang @szetszwo 

I found this `summary of failures` was pretty useful when I work with Ozone. So I can see a list of failed tests directly without the need to dig into the long log from running the unit tests.

**Comment by amaliujia** [comment]
This is the screenshot  to show that the `summary of  failures` is setup properly.

截屏2021-01-17 下午6 42 24

**Comment by runzhiwang** [comment]
@amaliujia Can we print more detailed message of failed ut in summary.txt ? For example:
image

**Comment by amaliujia** [comment]
@runzhiwang 

Currently that detailed error message is not printed into the summary.txt. We might can write customized script but that will need more work plus I guess those script will likely be fragile.

The summary of failed test name is useful already: we can know which has failed and go back to log to search the test name and then can find the error message.

**Comment by amaliujia** [comment]
Meanwhile I will leave the failed CI check here as this PR does not change any code. The failed CI check is also a way to approve this PR is working.

**Comment by runzhiwang** [comment]
@amaliujia Thanks the patch. I have merged it.

**Pull request merged**
