### PR TITLE
RATIS-1052. Fix the testDisconnectLeader assertion

### PR DESCRIPTION
**Pull request by maobaolong**
## What changes were proposed in this pull request?

Fix the testDisconnectLeader assertion in LeaderElectionTests.java, now the logic of that assertion is forever success, so, I fix it by this PR.

## What is the link to the Apache JIRA

RATIS-1052

## How was this patch tested?

It is already a test.

### CODE REVIEW

**Comment by maobaolong** [comment]
@runzhiwang Please take a look at this PR, I think the related test have a wrong assertion.

**Comment by runzhiwang** [comment]
+1

**Comment by runzhiwang** [comment]
@maobaolong Thanks the patch. I have merged it.

**Comment by amaliujia** [comment]
+1!

**Pull request closed without merging**
