### PR TITLE
RATIS-843: create ratis-docs module

### PR DESCRIPTION
**Pull request by esahekmat**
create a base structure for the project documentation

### CODE REVIEW

**Comment by esahekmat** [comment]
@elek why this merge request hasn't merged yet? does it have any problem?

**Comment by elek** [comment]
> @elek why this merge request hasn't merged yet? does it have any problem?

Because the Easter Holidays in Europe ;-) I am checking it right now, apologize for the delay...

**Comment by esahekmat** [comment]
Sorry, I think there is a problem related to this PR

**Comment by esahekmat** [comment]
I think you close this PR instead of merging it.

**Comment by elek** [comment]
I merge the commits locally because I prefer to sign the commits (which is not possible with the merge buttons). To have a reference between the PR I added an additional text to the commit message ("Closes #843") which closes the the PR automatically when I push the commit to the master.

If you click to the  2c8d550  commit from the previous message you can see that it's on the master.
 
This can be confusing, but the commits are signed ;-)

(The same are explained here: https://cwiki.apache.org/confluence/display/HADOOP/Using+Github+for+Ozone+development)

But I can make mistakes easily (usually I do), so feel free to ping me if the commit is missing from the master. In this case seems to be there.

**Pull request closed without merging**
