### PR TITLE
RATIS-1179. Add a new API to DataStreamOutput for sending a File.

### PR DESCRIPTION
**Pull request by szetszwo**
See https://issues.apache.org/jira/browse/RATIS-1179

### CODE REVIEW

**Comment by runzhiwang** [comment]
@szetszwo Thanks the great work, the improvement is awesome.  Now transferTo only work on client, but it did not work on primary.  

1. when primary store data to disk, the flow is: socket -> kernel space -> user space (DirectByteBuffer) -> kernel space -> disk
2. when primary send data to peer, the flow is: socket -> kernel space -> user space (DirectByteBuffer same to the previous) -> kernel space -> socket.  

And I think the ideal flow as follows, but I'm not sure whether can we achieve it.

1. when primary store data to disk, the flow is: socket -> kernel space -> disk
2. when primary send data to peer, the flow is: socket (or disk) -> kernel space -> socket

**Comment by szetszwo** [comment]
Good points.  For servers, we should use ByteBuf.writeBytes
https://netty.io/4.1/api/io/netty/buffer/ByteBuf.html#writeBytes-java.nio.channels.FileChannel-long-int-

Let's work on it in a separate JIRA.

**Comment by runzhiwang** [comment]
@szetszwo Thanks the great patch. I have merge it.

**Comment by szetszwo** [comment]
@runzhiwang ,  thanks for merging this.

Btw, just have checked FileChannelImpl.write(ByteBuffer).  It will call 
```
//FileChannelImpl.write
IOUtil.write(this.fd, var1, -1L, this.nd);
```
and then
```
//IOUtil.write
  static int write(FileDescriptor var0, ByteBuffer var1, long var2, NativeDispatcher var4) throws IOException {
    if (var1 instanceof DirectBuffer) {
      return writeFromNativeBuffer(var0, var1, var2, var4);
```
I suspect writeFromNativeBuffer is already zero-copy.  If it is the case, the current server implementation is working fine.

**Comment by runzhiwang** [comment]
@szetszwo Hi, I draw a diagram of the data flow: client -> primary -> peer, when we use transferTo. Do you have any other  suggestions about improving the flow efficiency ?
image

**Comment by szetszwo** [comment]
Your diagram looks very nice.  Could you post it on RATIS-1176?

Suppose the state machine only writes the data to files but not reading it or computing checksums.  Netty may be able to avoid moving it to the user space.  Need to check about it.

**Comment by runzhiwang** [comment]
@szetszwo Sure, let me post it on RATIS-1176

**Pull request merged**
