### PR TITLE
RATIS-965. Adds new JMX metric for getting Groups a server is part of

### PR DESCRIPTION
**Pull request by cyrus-jackson**
## What changes were proposed in this pull request?

This PR added a new jmx metric to show the Groups a server is part of.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/projects/RATIS/issues/RATIS-965

## How was this patch tested?

Manual test. I have tested this using Java Mission Control to check weather metrics are properly emitting or not.

### CODE REVIEW

**Comment by cyrus-jackson** [comment]
Failing tests are not related to the patch

**Comment by runzhiwang** [comment]
@cyrus-jackson Hi, You can push an empty commit by `git commit --allow-empty -m "triger ci"` to trigger CI again. The CI passed ratio is about 50%.

**Comment by cyrus-jackson** [comment]
@lokeshj1703 Can you please review the patch. Thanks in advance.

**Comment by lokeshj1703** [comment]
@cyrus-jackson Thanks for the contribution! I have committed the PR to master branch.

**Pull request closed without merging**
