### PR TITLE
RATIS-1300. Fix NPE from SegmentedRaftLogCache#getOpenSegmentSizeInBytes

### PR DESCRIPTION
**Pull request by runzhiwang**
## What changes were proposed in this pull request?

 Fix NPE from SegmentedRaftLogCache#getOpenSegmentSizeInBytes

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/RATIS-1300

## How was this patch tested?

no need new ut

### CODE REVIEW

**Comment by runzhiwang** [comment]
@elek Could you help review this ? Thanks a lot.

**Review by szetszwo — APPROVED** [review]
+1 the change looks good.

**Comment by amaliujia** [comment]
+1 thanks for this fix!

**Comment by runzhiwang** [comment]
@szetszwo @amaliujia Thanks for review. I have merged it.

**Pull request merged**
