### PR TITLE
RATIS-792. NPE. ServerOpts.metaQuorum should be required

### PR DESCRIPTION
**Pull request by maobaolong**

### CODE REVIEW

**Comment by joshelser** [comment]
I think this is fine. You do any testing with this change, @maobaolong ?

**Comment by maobaolong** [comment]
@jandrunas Thank you very much for your review. I've done test by execute MetadataServer without any argument.

With this PR.

Exception in thread "main" com.beust.jcommander.ParameterException: The following option is required: [-q | --metaQuorum]
	at com.beust.jcommander.JCommander.validateOptions(JCommander.java:381)
	at com.beust.jcommander.JCommander.parse(JCommander.java:341)
	at com.beust.jcommander.JCommander.parse(JCommander.java:319)
	at org.apache.ratis.logservice.server.MetadataServer.main(MetadataServer.java:121)

WIthout this PR.

Exception in thread "main" java.lang.NullPointerException
	at org.apache.ratis.logservice.util.LogServiceUtils.getPeersFromQuorum(LogServiceUtils.java:43)
	at org.apache.ratis.logservice.server.MetadataServer.start(MetadataServer.java:92)
	at org.apache.ratis.logservice.server.MetadataServer.main(MetadataServer.java:127)
	Suppressed: java.lang.NullPointerException
		at org.apache.ratis.logservice.server.MetadataServer.close(MetadataServer.java:145)
		at org.apache.ratis.logservice.server.MetadataServer.main(MetadataServer.java:136)

**Comment by runzhiwang** [comment]
+1

**Comment by lokeshj1703** [comment]
@maobaolong Can you please rebase and push an empty commit so that we get a CI run?

**Comment by maobaolong** [comment]
@lokeshj1703 Thanks for your review, this is my first blood for the ratis, I'd like to make more contribution after this. 😄

**Comment by maobaolong** [comment]
@arp7 Thank you very much for merge this for me

**Comment by lokeshj1703** [comment]
@maobaolong Looking forward to your contributions. :)

**Pull request merged**
