### PR TITLE
RATIS-1315. Fix child module ratis-server-api does not exist.

### PR DESCRIPTION
**Pull request by szetszwo**
See https://issues.apache.org/jira/browse/RATIS-1315

### CODE REVIEW

**Comment by szetszwo** [comment]
@runzhiwang, Could you try if this can fix the problem?

**Comment by runzhiwang** [comment]
@szetszwo Hi, it does work. Thanks.

**Comment by szetszwo** [comment]
@runzhiwang , thanks a lot for reviewing this.

BTW, we should migrate the podling from the Incubator to the TLP before the release; see https://issues.apache.org/jira/browse/RATIS-1316

**Comment by runzhiwang** [comment]
@szetszwo  Hi, not sure how long it will cost to migrate the podling from the Incubator to the TLP. Ozone community want this release urgently.

**Comment by szetszwo** [comment]
@runzhiwang, it should be easy for the releases.  We only have to remove DISCLAIMER file and make sure the artifact names do not contain "incubator" anymore.  The website and other changes can be done later.

**Pull request merged**
