### PR TITLE
RATIS-830. Add a metric for tracking failed client requests on a server

### PR DESCRIPTION
**Pull request by amaliujia**
## What changes were proposed in this pull request?

Add a metric for tracking failed client requests on a server

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/RATIS-830

## How was this patch tested?

UT

### CODE REVIEW

**Comment by amaliujia** [comment]
R: @bshashikant 

Can you take a look please?

**Review by bshashikant — COMMENTED** [review]
Thanks @amaliujia for working on this. Can we make it more granular as to track which type of request failed(WRITE,READ,WATCH,STREAM etc) and how many times?

**Comment by amaliujia** [comment]
@bshashikant 

That's a good idea. Will split metrics to different types of request.

**Comment by amaliujia** [comment]
@bshashikant

Updated to count on different types of failed requests. Can you take another look?

**Comment by runzhiwang** [comment]
@amaliujia Thanks the patch @bshashikant Thanks for review. I merged the patch.

**Comment by amaliujia** [comment]
@runzhiwang  thank you!

**Pull request merged**
