### PR TITLE
RATIS-1110. Fix DataStreamReply out of order.

### PR DESCRIPTION
**Pull request by szetszwo**
See https://issues.apache.org/jira/browse/RATIS-1110

### CODE REVIEW

**Comment by szetszwo** [comment]
Using thenCombineAsync somehow fixes the failure.  I suspect it is a Java bug.

@runzhiwang , could you test to see if it really can fix the failure?

**Comment by runzhiwang** [comment]
@szetszwo Sure, let me test it.

**Comment by runzhiwang** [comment]
@szetszwo Thanks the patch. After test, I'm sure this patch fix the failure.

**Comment by szetszwo** [comment]
@runzhiwang , thanks for merging this.  I have filed https://issues.apache.org/jira/browse/RATIS-1114 for some code cleanup.  Could you take a look?

**Comment by amaliujia** [comment]
> Using thenCombineAsync somehow fixes the failure. I suspect it is a Java bug.
> 
> @runzhiwang , could you test to see if it really can fix the failure?

Yes this is wired. My understanding to API with `Async` suffix is those calls are executed separately asynchronously, e.g. `thenSupplyAsync`. But maybe combine is different as combine really means it needs to depends on previous stage. 

Thanks for finding such subtle difference.

**Pull request merged**
