### PR TITLE
RATIS-1131. Refactor the notifyXxx() methods in StateMachine.

### PR DESCRIPTION
**Pull request by szetszwo**
See https://issues.apache.org/jira/browse/RATIS-1131

### CODE REVIEW

**Review by runzhiwang — APPROVED** [review]
LGTM,  need to fix check style error.

**Review by bshashikant — APPROVED** [review]
LGTM, apart from checkstyle issues.

**Comment by runzhiwang** [comment]
Reopen pr to trigger ci

**Comment by runzhiwang** [comment]
@szetszwo I trigger CI two times, but unit test both run a very long time.

**Comment by szetszwo** [comment]
Let's me check.  Some tests may be failing due to the change.

**Comment by szetszwo** [comment]
@runzhiwang and @bshashikant , thanks a lot for reviewing this.

**Pull request merged**
