### PR TITLE
RATIS-740. Fix checkstyle violations in ratis-common

### PR DESCRIPTION
**Pull request by dineshchitlangia**
**Proposed changes:**
This PR aims to fix checkstyle violations in ratis-common module

**Link to JIRA**
https://issues.apache.org/jira/browse/RATIS-740

**How was this patch tested?**
Build was successful using `mvn clean package -DskipTests`
Also executed all tests locally, few tests timed out as always in local.

### CODE REVIEW

**Comment by dineshchitlangia** [comment]
The test failures seem unrelated to patch. @joshelser / @szetszwo  could you pls review? Thanks.

**Comment by szetszwo** [comment]
Hi @dineshchitlangia , it seems that Jenkins is not working well for pull requests.  Could you post your patch on the JIRA?  (Or, do you want to see if you can fix the Jenkins for pull requests. :) )

**Comment by dineshchitlangia** [comment]
@szetszwo 

> do you want to see if you can fix the Jenkins for pull requests.

I would love to explore this area as I haven't worked with Jenkins before. So, I will file a jira and start exploring.

> Could you post your patch on the JIRA?
Sure, I will post a patch now. I request that when committing the patch, if possible we include the contributor email or once you sign off the patch, you can merge the PR (provided I ensure that both are exactly same). This helps to get the contributions show up on github profile :)

**Comment by joshelser** [comment]
see:

https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=89065396
https://docs.cloudbees.com/docs/admin-resources/latest/plugins/pull-request-builder-for-github

I've not done this new process for any ASF projects, so you will have some experimenting to do :). If you have karma on the ASF jenkins, then you should be able to start trying stuff out. builds@a.o will be a good resource.

**Pull request closed without merging**
