### PR TITLE
RATIS-1024.Unit Tests for MemoryRaftLog entry truncation

### PR DESCRIPTION
**Pull request by amaliujia**
## What changes were proposed in this pull request?
Add unit tests to test MemoryReftLog log truncation

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/RATIS-1024

Please replace this section with the link to the Apache JIRA)

## How was this patch tested?

unit tests

### CODE REVIEW

**Comment by amaliujia** [comment]
@szetszwo 

Per file history I am guessing you are the right person to review this PR. Can you take a look?

**Comment by szetszwo** [comment]
@amaliujia , could you see if the failed unit test is related?

**Comment by amaliujia** [comment]
@szetszwo

The failed UT is not related. `org.apache.ratis.TestMultiRaftGroup` has failed and I created https://issues.apache.org/jira/browse/RATIS-1026 to track it.

**Comment by szetszwo** [comment]
Thanks, @amaliujia .  I just have merged this.

**Comment by amaliujia** [comment]
Thank you!

**Pull request merged**
