### PR TITLE
RATIS-1166. Link DataStream with LogEntryProto.

### PR DESCRIPTION
**Pull request by szetszwo**
See https://issues.apache.org/jira/browse/RATIS-1166

### CODE REVIEW

**Comment by runzhiwang** [comment]
> Once a log entry is created for a DataStream, the server should link log entry with the DataStream so that the StateMachine must not delete the data unless the log entry is truncated.

@szetszwo Hi, I have one question. link log entry with the DataStream is aim for we can delete the data when truncate the log entry ?

**Comment by szetszwo** [comment]
Yes, one of the goals is to let state machine delete the data when truncating the log entry.

Another goal is to replicate the data with the log entry to other servers (not yet implemented).

The idea is similar to the state machine data stored by StateMachine.DataApi.write(..).  The state machine should manage the stream data the same way.

**Comment by runzhiwang** [comment]
@szetszwo Got it. Thanks for explanation.

**Review by runzhiwang — APPROVED** [review]
LGTM

**Pull request merged**
