### PR TITLE
RATIS-1281. TestRetryCacheWithGrpc#testRetryOnResourceUnavailableException fails

### PR DESCRIPTION
**Pull request by ferhui**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## What is the link to the Apache JIRA

(Please create an issue in ASF JIRA before opening a pull request,
and you need to set the title of the pull request which starts with
the corresponding JIRA issue number. (e.g. RATIS-XXXX. Fix a typo in YYY.)

Please replace this section with the link to the Apache JIRA)

## How was this patch tested?

(Please explain how this patch was tested. Ex: unit tests, manual tests)
(If this patch involves UI changes, please attach a screen-shot; otherwise, remove this)

### CODE REVIEW

**Comment by ferhui** [comment]
@lokeshj1703 Hi, i see you add this test, could you please take a look? Thanks

**Comment by ferhui** [comment]
Detail about this PR, I have post it to jira, and paste it here.

The first while clause in TestRetryCacheWithGrpc#testRetryOnResourceUnavailableException
```
while (!failure.get()) {
  long cid = callId;
  r = cluster.newRaftClientRequest(clientId, leaderProxy.getId(), callId++,
      new RaftTestUtil.SimpleMessage("message"));
  CompletableFuture<RaftClientReply> f = leaderProxy.submitClientRequestAsync(r);
  f.exceptionally(e -> {
      if (e.getCause() instanceof ResourceUnavailableException) {
        RetryCacheTestUtil.isFailed(RetryCacheTestUtil.get(leader, clientId, cid));
        failure.set(true);
      }
      return null;
  });
}
```

There are 2 requests here, and because followers call blockWriteStateMachineData, the first request will be blocked, and ELEMENT_LIMIT_KEY is 1, the second request will fail and receive ResourceUnavailableException.

After quittng the first while clause. Followers call unblockWriteStateMachineData

In the second while clause
```
while (failure.get()) {
  try {
  // retry until the request failed with ResourceUnavailableException succeeds.
  leaderProxy.submitClientRequestAsync(r).get();
  } catch (Exception e) {
    failure.set(false);
  }
}
```

There are 2 cases: 1. If the first request has been done, the 3rd request will be handled, and later requests will hit retrycache, and server will always return success. It couldn't get Exception and enter infinite loop. 2. If the first request hasn't been done, and the 3rd request has been reach the server, it will get   ResourceUnavailableException and set failure true, and quit the loop.

Mostly the case 1 occurs, and this UT nearly always fails

So i suggest that quit the loop when request handled successfully as the comments say

> // retry until the request failed with ResourceUnavailableException succeeds.

**Review by lokeshj1703 — APPROVED** [review]
@ferhui Thanks for working on this! The changes look good to me. +1.

**Comment by lokeshj1703** [comment]
@ferhui Can you please update the PR description as well?

**Comment by lokeshj1703** [comment]
@ferhui Thanks for the contribution! I have committed the PR to master branch. The test failures in CI are unrelated as PR only has changes in a test file.

**Comment by ferhui** [comment]
@lokeshj1703 Thanks for review!

**Pull request closed without merging**
